// (c) 2025 Sam Caldwell. All Rights Reserved.
#include "basic_compiler/codegen/CodeGenerator.h"
#include <sstream>

namespace gwbasic {

/*
 * Function: emitHeader
 * Summary: Emit module banner and external declarations used by IR.
 * Parameters:
 *  - out: IR output stream to append to.
 * Returns:
 *  - void
 */
void CodeGenerator::emitHeader(std::ostringstream& out) {
    out << ";; Generated by gwbasic::CodeGenerator" << Symbols::LF << Symbols::LF
        << "declare i32 @printf(ptr, ...)" << Symbols::LF
        << "declare i32 @scanf(ptr, ...)" << Symbols::LF
        << "declare i32 @snprintf(ptr, i64, ptr, ...)" << Symbols::LF
        << "declare i32 @strcmp(ptr, ptr)" << Symbols::LF
        << "declare i64 @strlen(ptr)" << Symbols::LF
        << "declare ptr @strstr(ptr, ptr)" << Symbols::LF
        << "declare ptr @strchr(ptr, i32)" << Symbols::LF
        << "declare ptr @malloc(i64)" << Symbols::LF
        << "declare ptr @strcpy(ptr, ptr)" << Symbols::LF
        << "declare ptr @strcat(ptr, ptr)" << Symbols::LF << Symbols::LF
        << "declare ptr @popen(ptr, ptr)" << Symbols::LF
        << "declare i32 @pclose(ptr)" << Symbols::LF
        << "declare ptr @strncpy(ptr, ptr, i64)" << Symbols::LF
        << "declare ptr @memset(ptr, i32, i64)" << Symbols::LF
        << "declare ptr @fgets(ptr, i32, ptr)" << Symbols::LF
    // File I/O
        << "declare ptr @fopen(ptr, ptr)" << Symbols::LF
        << "declare i32 @fclose(ptr)" << Symbols::LF
        << "declare i32 @fprintf(ptr, ptr, ...)" << Symbols::LF
        << "declare i32 @fscanf(ptr, ptr, ...)" << Symbols::LF
        << "declare i64 @fread(ptr, i64, i64, ptr)" << Symbols::LF
        << "declare i64 @fwrite(ptr, i64, i64, ptr)" << Symbols::LF << Symbols::LF
        << "declare i32 @chdir(ptr)" << Symbols::LF
        << "declare i32 @mkdir(ptr, i32)" << Symbols::LF
        << "declare i32 @rmdir(ptr)" << Symbols::LF
        << "declare i32 @remove(ptr)" << Symbols::LF
        << "declare i32 @rename(ptr, ptr)" << Symbols::LF
        << "declare i32 @system(ptr)" << Symbols::LF
        << "declare i32 @setenv(ptr, ptr, i32)" << Symbols::LF
        << "declare i32 @unsetenv(ptr)" << Symbols::LF << Symbols::LF
    // Math library functions used by intrinsic calls
        << "declare double @sqrt(double)" << Symbols::LF
        << "declare double @fabs(double)" << Symbols::LF
        << "declare double @sin(double)" << Symbols::LF
        << "declare double @cos(double)" << Symbols::LF
        << "declare double @tan(double)" << Symbols::LF
        << "declare double @atan(double)" << Symbols::LF
        << "declare double @log(double)" << Symbols::LF
        << "declare double @exp(double)" << Symbols::LF
        << "declare double @pow(double, double)" << Symbols::LF
        << "declare double @floor(double)" << Symbols::LF << Symbols::LF
    // Additional helpers for extended math/CVT
        << "declare double @drand48()" << Symbols::LF
        << "declare double @round(double)" << Symbols::LF << Symbols::LF
    // Conversion
        << "declare double @strtod(ptr, ptr)" << Symbols::LF << Symbols::LF
    // RNG seed + time
        << "declare void @srand48(i64)" << Symbols::LF
        << "declare i64 @time(ptr)" << Symbols::LF
        << "declare ptr @localtime(ptr)" << Symbols::LF
        << "declare i64 @strftime(ptr, i64, ptr, ptr)" << Symbols::LF << Symbols::LF
        << "declare ptr @getenv(ptr)" << Symbols::LF << Symbols::LF;

    // Provide helper implementing full RND(x) semantics if needed
    if (needsRndHelper_) {
        out << "define double @gwb_rnd(double %x) {" << Symbols::LF
            << "entry:" << Symbols::LF
            << "  %iszero = fcmp oeq double %x, 0.0" << Symbols::LF
            << "  br i1 %iszero, label %retlast, label %nonzero" << Symbols::LF
            << "retlast:" << Symbols::LF
            << "  %lastf = load float, ptr @gwb_last_rnd" << Symbols::LF
            << "  %last = fpext float %lastf to double" << Symbols::LF
            << "  ret double %last" << Symbols::LF
            << "nonzero:" << Symbols::LF
            << "  %isneg = fcmp olt double %x, 0.0" << Symbols::LF
            << "  br i1 %isneg, label %seedcase, label %gen" << Symbols::LF
            << "seedcase:" << Symbols::LF
            << "  %xi = fptosi double %x to i64" << Symbols::LF
            << "  call void @srand48(i64 %xi)" << Symbols::LF
            << "  br label %gen" << Symbols::LF
            << "gen:" << Symbols::LF
            << "  %rv = call double @drand48()" << Symbols::LF
            << "  %rvf = fptrunc double %rv to float" << Symbols::LF
            << "  store float %rvf, ptr @gwb_last_rnd" << Symbols::LF
            << "  %rve = fpext float %rvf to double" << Symbols::LF
            << "  ret double %rve" << Symbols::LF
            << "}" << Symbols::LF << Symbols::LF;
    }
    // Provide a minimal CALL helper that interprets the first byte at the
    // effective address as an opcode. Currently, opcode 1 prints "CALLED\n".
    out << "define void @gwb_call(i64 %addr) {" << Symbols::LF
        << "entry:" << Symbols::LF
        << "  %p = getelementptr inbounds [1048576 x i8], ptr @gwb_mem, i64 0, i64 %addr" << Symbols::LF
        << "  %op = load i8, ptr %p" << Symbols::LF
        << "  %is1 = icmp eq i8 %op, 1" << Symbols::LF
        << "  br i1 %is1, label %case1, label %ret" << Symbols::LF
        << "case1:" << Symbols::LF
        << "  %fmt = getelementptr inbounds i8, ptr @.call_msg, i64 0" << Symbols::LF
        << "  call i32 (ptr, ...) @printf(ptr %fmt)" << Symbols::LF
        << "  br label %ret" << Symbols::LF
        << "ret:" << Symbols::LF
        << "  ret void" << Symbols::LF
        << "}" << Symbols::LF << Symbols::LF;
    // Helper: list directory entries using popen("ls -1 ...") and print to stdout or device
    out << "define void @gwb_list_files(ptr %dev, ptr %pat) {" << Symbols::LF
        << "entry:" << Symbols::LF
        << "  %prefix = getelementptr inbounds [7 x i8], ptr @.str_ls1sp, i64 0, i64 0" << Symbols::LF
        << "  %dot = getelementptr inbounds [2 x i8], ptr @.str_dot, i64 0, i64 0" << Symbols::LF
        << "  %pat_is_null = icmp eq ptr %pat, null" << Symbols::LF
        << "  %pat_eff = select i1 %pat_is_null, ptr %dot, ptr %pat" << Symbols::LF
        << "  %cmd = call ptr @malloc(i64 512)" << Symbols::LF
        << "  call ptr @strcpy(ptr %cmd, ptr %prefix)" << Symbols::LF
        << "  call ptr @strcat(ptr %cmd, ptr %pat_eff)" << Symbols::LF
        << "  %pipe = call ptr @popen(ptr %cmd, ptr @.mode_r)" << Symbols::LF
        << "  br label %loop" << Symbols::LF
        << "loop:" << Symbols::LF
        << "  %buf = getelementptr inbounds [256 x i8], ptr @gwb_sbuf, i64 0, i64 0" << Symbols::LF
        << "  %got = call ptr @fgets(ptr %buf, i32 256, ptr %pipe)" << Symbols::LF
        << "  %eof = icmp eq ptr %got, null" << Symbols::LF
        << "  br i1 %eof, label %done, label %body" << Symbols::LF
        << "body:" << Symbols::LF
        << "  %dev_null = icmp eq ptr %dev, null" << Symbols::LF
        << "  br i1 %dev_null, label %to_stdout, label %chk_dev" << Symbols::LF
        << "chk_dev:" << Symbols::LF
        << "  %lpt = getelementptr inbounds [6 x i8], ptr @.str_lpt1, i64 0, i64 0" << Symbols::LF
        << "  %cmp = call i32 @strcmp(ptr %dev, ptr %lpt)" << Symbols::LF
        << "  %is_lpt = icmp eq i32 %cmp, 0" << Symbols::LF
        << "  br i1 %is_lpt, label %try_prn, label %to_stdout" << Symbols::LF
        << "try_prn:" << Symbols::LF
        << "  %p0p = getelementptr inbounds [16 x ptr], ptr @gwb_files, i64 0, i64 0" << Symbols::LF
        << "  %fp = load ptr, ptr %p0p" << Symbols::LF
        << "  %fp_null = icmp eq ptr %fp, null" << Symbols::LF
        << "  br i1 %fp_null, label %to_stdout, label %do_prn" << Symbols::LF
        << "do_prn:" << Symbols::LF
        << "  %fmtp = getelementptr inbounds [3 x i8], ptr @.fmt_str_sp, i64 0, i64 0" << Symbols::LF
        << "  call i32 @fprintf(ptr %fp, ptr %fmtp, ptr %buf)" << Symbols::LF
        << "  br label %cont" << Symbols::LF
        << "to_stdout:" << Symbols::LF
        << "  %fmts = getelementptr inbounds [3 x i8], ptr @.fmt_str_sp, i64 0, i64 0" << Symbols::LF
        << "  call i32 (ptr, ...) @printf(ptr %fmts, ptr %buf)" << Symbols::LF
        << "  br label %cont" << Symbols::LF
        << "cont:" << Symbols::LF
        << "  br label %loop" << Symbols::LF
        << "done:" << Symbols::LF
        << "  call i32 @pclose(ptr %pipe)" << Symbols::LF
        << "  ret void" << Symbols::LF
        << "}" << Symbols::LF << Symbols::LF;
    // Graphics initializer used by SCREEN statement
    // - Sets @gwb_gfx_ready = true when mode > 0 and environment appears capable
    //   (DISPLAY or WAYLAND_DISPLAY is set) and not explicitly disabled; can
    //   be forced via GWBASIC_ENABLE_GFX. Text mode (<=0) disables graphics.
    out << "define void @gwb_graphics_init(i32 %mode) {" << Symbols::LF
        << "entry:" << Symbols::LF
        << "  %istext = icmp sle i32 %mode, 0" << Symbols::LF
        << "  br i1 %istext, label %setfalse, label %checkenv" << Symbols::LF
        << "setfalse:" << Symbols::LF
        << "  store i1 false, ptr @gwb_gfx_ready" << Symbols::LF
        << "  br label %ret" << Symbols::LF
        << "checkenv:" << Symbols::LF
        << "  %pdisp = getelementptr inbounds [8 x i8], ptr @.env_display, i64 0, i64 0" << Symbols::LF
        << "  %disp = call ptr @getenv(ptr %pdisp)" << Symbols::LF
        << "  %hasdisp = icmp ne ptr %disp, null" << Symbols::LF
        << "  %pway = getelementptr inbounds [16 x i8], ptr @.env_wayland, i64 0, i64 0" << Symbols::LF
        << "  %way = call ptr @getenv(ptr %pway)" << Symbols::LF
        << "  %hasway = icmp ne ptr %way, null" << Symbols::LF
        << "  %prob = or i1 %hasdisp, %hasway" << Symbols::LF
        << "  br i1 %prob, label %settrue, label %setfalse" << Symbols::LF
        << "settrue:" << Symbols::LF
        << "  store i1 true, ptr @gwb_gfx_ready" << Symbols::LF
        << "  br label %ret" << Symbols::LF
        << "ret:" << Symbols::LF
        << "  ret void" << Symbols::LF
        << "}" << Symbols::LF << Symbols::LF
        // Stub: draw circle/arc/ellipse (no-op); executed only when @gwb_gfx_ready is true
        // Params: cx, cy, r, color (-1=default), start (-1=full), end, aspect (-1=1.0), step (ignored)
        << "define void @gwb_gfx_circle(double %cx, double %cy, double %r, i32 %color, double %start, double %end, double %aspect, i1 %step) {" << Symbols::LF
        << "entry:" << Symbols::LF
        << "  ret void" << Symbols::LF
        << "}" << Symbols::LF << Symbols::LF;
    // Helper: write a buffer of bytes to the virtual screen, updating cursor
    // - Advances column/row, wraps at dynamic width (@gwb_screen_cols) and 25 rows, handles '\n' by CR+LF behavior
    out << "define void @gwb_screen_write(ptr %buf, i64 %len) {" << Symbols::LF
        << "entry:" << Symbols::LF
        << "  %w = load i32, ptr @gwb_screen_cols" << Symbols::LF
        << "  br label %loop" << Symbols::LF
        << "loop:" << Symbols::LF
        << "  %i = phi i64 [ 0, %entry ], [ %inc, %cont ]" << Symbols::LF
        << "  %cond = icmp slt i64 %i, %len" << Symbols::LF
        << "  br i1 %cond, label %body, label %ret" << Symbols::LF
        << "body:" << Symbols::LF
        << "  %p = getelementptr inbounds i8, ptr %buf, i64 %i" << Symbols::LF
        << "  %ch = load i8, ptr %p" << Symbols::LF
        << "  %islf = icmp eq i8 %ch, 10" << Symbols::LF
        << "  br i1 %islf, label %do_lf, label %do_char" << Symbols::LF
        << "do_lf:" << Symbols::LF
        << "  store i32 0, ptr @gwb_cur_col" << Symbols::LF
        << "  %r0 = load i32, ptr @gwb_cur_row" << Symbols::LF
        << "  %r1 = add i32 %r0, 1" << Symbols::LF
        << "  %rwrap = icmp eq i32 %r1, 25" << Symbols::LF
        << "  %rnew = select i1 %rwrap, i32 0, i32 %r1" << Symbols::LF
        << "  store i32 %rnew, ptr @gwb_cur_row" << Symbols::LF
        << "  br label %cont" << Symbols::LF
        << "do_char:" << Symbols::LF
        << "  %r2 = load i32, ptr @gwb_cur_row" << Symbols::LF
        << "  %c2 = load i32, ptr @gwb_cur_col" << Symbols::LF
        << "  %r80 = mul i32 %r2, 80" << Symbols::LF
        << "  %idx32 = add i32 %r80, %c2" << Symbols::LF
        << "  %idx64 = sext i32 %idx32 to i64" << Symbols::LF
        << "  %dst = getelementptr inbounds [2000 x i8], ptr @gwb_screen, i64 0, i64 %idx64" << Symbols::LF
        << "  store i8 %ch, ptr %dst" << Symbols::LF
        << "  %c3 = add i32 %c2, 1" << Symbols::LF
        << "  %cwrap = icmp eq i32 %c3, %w" << Symbols::LF
        << "  br i1 %cwrap, label %do_wrap, label %do_storecol" << Symbols::LF
        << "do_wrap:" << Symbols::LF
        << "  store i32 0, ptr @gwb_cur_col" << Symbols::LF
        << "  %r3 = load i32, ptr @gwb_cur_row" << Symbols::LF
        << "  %r4 = add i32 %r3, 1" << Symbols::LF
        << "  %rwrap2 = icmp eq i32 %r4, 25" << Symbols::LF
        << "  %rnew2 = select i1 %rwrap2, i32 0, i32 %r4" << Symbols::LF
        << "  store i32 %rnew2, ptr @gwb_cur_row" << Symbols::LF
        << "  br label %cont" << Symbols::LF
        << "do_storecol:" << Symbols::LF
        << "  store i32 %c3, ptr @gwb_cur_col" << Symbols::LF
        << "  br label %cont" << Symbols::LF
        << "cont:" << Symbols::LF
        << "  %inc = add i64 %i, 1" << Symbols::LF
        << "  br label %loop" << Symbols::LF
        << "ret:" << Symbols::LF
        << "  ret void" << Symbols::LF
        << "}" << Symbols::LF << Symbols::LF;
    // Global table for file channels (1..16)
    out << "@gwb_files = internal global [16 x ptr] zeroinitializer" << Symbols::LF << Symbols::LF;
    // Safe string helper: return empty string when given null pointer
    out << "define ptr @gwb_safe_str(ptr %p) {" << Symbols::LF
        << "entry:" << Symbols::LF
        << "  %isnull = icmp eq ptr %p, null" << Symbols::LF
        << "  %empty = getelementptr inbounds [1 x i8], ptr @.str_empty, i64 0, i64 0" << Symbols::LF
        << "  %ret = select i1 %isnull, ptr %empty, ptr %p" << Symbols::LF
        << "  ret ptr %ret" << Symbols::LF
        << "}" << Symbols::LF << Symbols::LF;
    // stdin handle (external) for LINE INPUT from console
    out << "@stdin = external global ptr" << Symbols::LF << Symbols::LF;
    log() << "emitHeader: declared stdio + globals" << Symbols::LF;
}

} // namespace gwbasic
