// (c) 2025 Sam Caldwell. All Rights Reserved.
#include "basic_compiler/codegen/CodeGenerator.h"
#include <sstream>

namespace gwbasic {

void CodeGenerator::emitHeader(std::ostringstream& out) {
    /*
     * Function: CodeGenerator::emitHeader
     * Inputs:
     *  - out: IR output stream to append to
     * Outputs:
     *  - void
     * Theory of operation:
     *  - Writes a generation banner and external declarations (printf/scanf)
     *    needed by the emitted IR.
     */
    out << ";; Generated by gwbasic::CodeGenerator\n\n";
    out << "declare i32 @printf(ptr, ...)\n";
    out << "declare i32 @scanf(ptr, ...)\n";
    out << "declare i32 @strcmp(ptr, ptr)\n\n";
    // Math library functions used by intrinsic calls
    out << "declare double @sqrt(double)\n";
    out << "declare double @fabs(double)\n";
    out << "declare double @sin(double)\n";
    out << "declare double @cos(double)\n";
    out << "declare double @tan(double)\n";
    out << "declare double @atan(double)\n";
    out << "declare double @log(double)\n";
    out << "declare double @exp(double)\n";
    out << "declare double @floor(double)\n\n";
    // Additional helpers for extended math/CVT
    out << "declare double @drand48()\n";
    out << "declare double @round(double)\n\n";
    log("emitHeader: declared printf/scanf");
}

} // namespace gwbasic
