// (c) 2025 Sam Caldwell. All Rights Reserved.
#include "basic_compiler/codegen/CodeGenerator.h"
#include <sstream>

namespace gwbasic {

void CodeGenerator::emitHeader(std::ostringstream& out) {
    /*
     * Function: CodeGenerator::emitHeader
     * Inputs:
     *  - out: IR output stream to append to
     * Outputs:
     *  - void
     * Theory of operation:
     *  - Writes a generation banner and external declarations (printf/scanf)
     *    needed by the emitted IR.
     */
    out << ";; Generated by gwbasic::CodeGenerator\n\n"
        << "declare i32 @printf(ptr, ...)\n"
        << "declare i32 @scanf(ptr, ...)\n"
        << "declare i32 @strcmp(ptr, ptr)\n"
        << "declare i64 @strlen(ptr)\n"
        << "declare ptr @malloc(i64)\n"
        << "declare ptr @strcpy(ptr, ptr)\n"
        << "declare ptr @strcat(ptr, ptr)\n\n"
    // File I/O
        << "declare ptr @fopen(ptr, ptr)\n"
        << "declare i32 @fclose(ptr)\n"
        << "declare i32 @fprintf(ptr, ptr, ...)\n\n"
        << "declare double @atof(ptr)\n\n"
    // Math library functions used by intrinsic calls
        << "declare double @sqrt(double)\n"
        << "declare double @fabs(double)\n"
        << "declare double @sin(double)\n"
        << "declare double @cos(double)\n"
        << "declare double @tan(double)\n"
        << "declare double @atan(double)\n"
        << "declare double @log(double)\n"
        << "declare double @exp(double)\n"
        << "declare double @floor(double)\n\n"
    // Additional helpers for extended math/CVT
        << "declare double @drand48()\n"
        << "declare double @round(double)\n\n"
    // RNG seed + time
        << "declare void @srand48(i64)\n"
        << "declare i64 @time(ptr)\n\n";

    // Provide helper implementing full RND(x) semantics if needed
    if (needsRndHelper_) {
        out << "define double @gwb_rnd(double %x) {\n"
            << "entry:\n"
            << "  %iszero = fcmp oeq double %x, 0.0\n"
            << "  br i1 %iszero, label %retlast, label %nonzero\n"
            << "retlast:\n"
            << "  %last = load double, ptr @gwb_last_rnd\n"
            << "  ret double %last\n"
            << "nonzero:\n"
            << "  %isneg = fcmp olt double %x, 0.0\n"
            << "  br i1 %isneg, label %seedcase, label %gen\n"
            << "seedcase:\n"
            << "  %xi = fptosi double %x to i64\n"
            << "  call void @srand48(i64 %xi)\n"
            << "  br label %gen\n"
            << "gen:\n"
            << "  %rv = call double @drand48()\n"
            << "  store double %rv, ptr @gwb_last_rnd\n"
            << "  ret double %rv\n"
            << "}\n\n";
    }
    // Global table for file channels (1..16)
    out << "@gwb_files = internal global [16 x ptr] zeroinitializer\n\n";
    log("emitHeader: declared stdio + globals");
}

} // namespace gwbasic
